### ISSUE TITLE
Missing assets for v0.7.1 release

### ISSUE THREAD

**Issue by eidekrist** [open-simulation-platform/cosim-cli#106]
The v0.7.1 release is missing two assets:
- cosim-v0.7.1-win64.zip
- cosim-v0.7.1-linux64-gcc9.zip

I'm assigning this to you @davidhjp01 as you performed the release. Maybe the missing assets can be dug out from Actions or the OSP Conan repo?

**Comment by davidhjp01** [comment]
I will look into it

**Comment by davidhjp01** [comment]
They are uploaded: https://github.com/open-simulation-platform/cosim-cli/releases/tag/v0.7.1

**Comment by davidhjp01** [comment]
Uploaded: https://github.com/open-simulation-platform/cosim-cli/releases/tag/v0.7.1
