### ISSUE TITLE
cosim run-single mixing windows and linux paths

### ISSUE THREAD

**Issue by frl000** [open-simulation-platform/cosim-cli#85]
The current release cosim-cli/v0.5.0 does fail in the form
```C:\>cosim.exe run-single C:\PATH\OspSystemStructure.xml```
with error message
```error: No resolvers available to handle URI: file:///C:/PATH/OspSystemStructure.xml```
Specifying relative paths ends up in error message
```error: internal: cosim::path_to_file_uri: Input requirement not satisfied: path.empty() || path.has_root_directory()```
Tested on W10.0.17763, command.exe

**Comment by ljamt** [comment]
> The current release cosim-cli/v0.5.0 does fail in the form `C:\>cosim.exe run-single C:\PATH\OspSystemStructure.xml` with error message `error: No resolvers available to handle URI: file:///C:/PATH/OspSystemStructure.xml` 

This is expected as the run-single command can only be used for `.fmu` files.

>Specifying relative paths ends up in error message `error: internal: cosim::path_to_file_uri: Input requirement not satisfied: path.empty() || path.has_root_directory()`

Using relative paths for fmus when running `inspect`and `run-single` will be solved with #98
